# docker/Dockerfile.edge
FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 python3-pip portaudio19-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml ./
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

COPY src ./src

CMD ["python3", "-m", "separation.cli", "--stem=vocals"]
